-- CreateIndex
-- Generated by Prisma, then edited by hand to add NULLS LAST, which Prisma
-- cannot express. It lets the end-user list's
-- ORDER BY last_signed_in_at DESC NULLS LAST, id DESC read the index in order
-- instead of sorting all of the Application's users.
CREATE INDEX "end_users_application_id_last_signed_in_at_desc_id_idx" ON "end_users"("application_id", "last_signed_in_at" DESC NULLS LAST, "id" DESC);
