/**
 * Regenerates src/lib/disposable-domains.data.ts from the
 * disposable-email-domains project (CC0 1.0).
 *
 *   pnpm --filter @rekey.dev/api disposable:refresh            # latest main
 *   pnpm --filter @rekey.dev/api disposable:refresh <commit>   # a pinned commit
 *
 * The list is vendored so sign-up never depends on a network fetch. Review the
 * diff before committing: a domain appearing here blocks sign-up for every
 * Application that turned `blockDisposable` on.
 */

import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = 'disposable-email-domains/disposable-email-domains';
const LIST_FILE = 'disposable_email_blocklist.conf';
const DOMAIN = /^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9-]{2,63}$/;

async function resolveCommit(ref: string): Promise<string> {
  if (/^[0-9a-f]{40}$/.test(ref)) return ref;
  const res = await fetch(`https://api.github.com/repos/${REPO}/commits/${ref}`, {
    headers: { accept: 'application/vnd.github+json' },
  });
  if (!res.ok) throw new Error(`could not resolve ${ref}: HTTP ${res.status}`);
  return ((await res.json()) as { sha: string }).sha;
}

async function main(): Promise<void> {
  const commit = await resolveCommit(process.argv[2] ?? 'main');
  const res = await fetch(`https://raw.githubusercontent.com/${REPO}/${commit}/${LIST_FILE}`);
  if (!res.ok) throw new Error(`could not download the list: HTTP ${res.status}`);
  const domains = [
    ...new Set(
      (await res.text())
        .split('\n')
        .map((l) => l.trim().toLowerCase())
        .filter((l) => l !== '' && !l.startsWith('#') && DOMAIN.test(l)),
    ),
  ].sort();
  if (domains.length < 1000) {
    throw new Error(`only ${domains.length} domains parsed; refusing to write a truncated list`);
  }

  const out = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    '../src/lib/disposable-domains.data.ts',
  );
  const body =
    '// GENERATED by apps/api/scripts/refresh-disposable-domains.mts. Do not edit by hand.\n' +
    `// Source: https://github.com/${REPO} (${LIST_FILE})\n` +
    '// Licence: CC0 1.0 Universal (public domain dedication).\n\n' +
    `export const DISPOSABLE_DOMAINS_SOURCE_COMMIT = '${commit}';\n` +
    `export const DISPOSABLE_DOMAINS_GENERATED_AT = '${new Date().toISOString().slice(0, 10)}';\n\n` +
    '/** One domain per line, lowercase ASCII (punycode), sorted. */\n' +
    'export const DISPOSABLE_DOMAINS_TEXT = `\n' +
    domains.join('\n') +
    '\n`;\n';
  writeFileSync(out, body);
  console.log(`wrote ${domains.length} domains from ${commit} to ${out}`);
}

await main();
